---
all:
  # Update your VM or bare-metal IP address
  hosts: 192.168.5.50
  vars:
    ansible_user: "ubuntu"
    orc8r_domain: "galaxy.shubhamtatvamasi.com"
    # deploy_on_aws: true
    # deploy_domain_proxy: true
    # magma_docker_registry: "venkonetworks"
    # magma_docker_tag: "v1.8.0-master"
    # orc8r_helm_repo: "https://venko-networks.github.io/magma-charts/"
