---
- name: Install Docker
  become: yes
  shell: |
    curl https://releases.rancher.com/install-docker/{{ docker_version }}.sh | sh

- name: Add user to docker group
  become: yes
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- name: Enable service docker
  when: ansible_os_family == "RedHat"
  become: yes
  service:
    name: docker
    enabled: yes

- name: Start service docker
  when: ansible_os_family == "RedHat"
  service:
    name: docker
    state: started

- name: Pull alpine docker image
  become: yes
  community.docker.docker_image:
    name: alpine
    source: pull
